name: Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install -yq libtool-bin libvorbisidec-dev curl git wget
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: cache boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: boost_1_78_0
        key: ${{ runner.os }}-boost
    - name: get boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: wget https://boostorg.jfrog.io/artifactory/main/release/1.78.0/source/boost_1_78_0.tar.bz2 && tar xjf boost_1_78_0.tar.bz2
    - name: build aar
      run: NDK_DIR=$ANDROID_NDK_HOME ./build_android.sh
    - name: github package
      run: |
        LIB="flac"
        VERSION="1.3.3"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="ogg"
        VERSION="1.3.5"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="opus"
        VERSION="1.1.2"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="tremor"
        VERSION="1.0.0"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="oboe"
        VERSION="1.6.1"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="soxr"
        VERSION="0.1.3"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="boost"
        VERSION="1.78.0"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv

        LIB="vorbis"
        VERSION="1.3.7"
        echo "<project><modelVersion>4.0.0</modelVersion><groupId>com.github.badaix</groupId><artifactId>$LIB</artifactId><version>$VERSION</version></project>" > /home/runner/work/snapcast-deps/$LIB-$VERSION.pom
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.pom" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/$LIB-$VERSION.pom" -vvv
        curl -X PUT "https://maven.pkg.github.com/k0hax/snapcast-deps/com/github/badaix/$LIB/$VERSION/$LIB-$VERSION.aar" -H "Authorization:token ${{ secrets.GITHUB_TOKEN }}" --upload-file "/home/runner/work/snapcast-deps/snapcast-deps/build/aar/$LIB-$VERSION.aar" -vvv
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: develop_snapshot-${{github.sha}}
        path: /home/runner/work/snapcast-deps/snapcast-deps/build/aar/*.aar
